AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  ApplicationName:
    Type: String
    Description: The name of the application to deploy
  EnvironmentName:
    Type: String
    Description: The name of the environment to deploy


Resources:
  InventoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ApplicationName}-${EnvironmentName}-inventory
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ApplicationName}-${EnvironmentName}
      # AccelerateConfiguration:
      #   AccelerationStatus: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      InventoryConfigurations:
        - Id: DailyInventoryReports
          Enabled: true
          IncludedObjectVersions: All
          ScheduleFrequency: Daily
          Destination:
            BucketArn: !GetAtt InventoryBucket.Arn
            Format: CSV

  StorageLens:
    Type: AWS::S3::StorageLens
    Properties:
      StorageLensConfiguration:
        Id: !Sub ${ApplicationName}-${EnvironmentName}
        IsEnabled: True
        AccountLevel:
          BucketLevel: {}
        Include:
          Buckets:
            - !GetAtt Bucket.Arn


Outputs:
  BucketName:
    Value: !Ref Bucket
